aws:
  region: ap-northeast-1
  ml_bucket: s3://ml-bucket
  source_bucket: s3://source-bucket
  ssm_cloud_sql_info: /ssm/service/ml/cloud-sql/connection_info
  ssm_gcp_service_account: /ssm/service/ml/gcp-service-account/account

gcp:
  project_id: gcp-project-id
  ml_bucket: gs://ml-bucket
  secret_manager:
    ml_cloud_sql: 
      name: ml-cloud-sql
      version: 3
    ml_slack: 
      name: ml-slack
      version: 1
    labeling_service:
      name: datasaur-credential
      version: 1

gcp_data_transfer:
  aws_s3_data_source: ml-data-production
  gcs_data_source: ml-data-production
  timeout: 10800

airflow_connection_ids:
  slack_conn_id: slack-conn
  aws_conn_id: ml-aws-conn
  gcp_conn_id: gcp-conn
  gcp_cloud_sql_conn_id: ml-cloud-sql-conn
  gcp_data_transfer_conn_id: aws-gcp-datatransfer-conn
  ml_slack: 
    conn_id: ml-slack-conn
    post_channel: "#airflow-alerts"
